### ISSUE TITLE
the tool is not accepting sign up 

### ISSUE THREAD

**Issue by Omicsense** [saowwapark/inCNV#2] opened 2021-04-03 06:53 UTC
Hello,

i just installed the tool and when i try to create user using the signup button it give me the dialog to enter the username and password then i click signup it gives me Erro and no users created.
<img width="1248" alt="Screen Shot 2021-04-03 at 8 53 33 AM" src="https://user-images.githubusercontent.com/50102341/113471052-1548eb80-945a-11eb-8fa9-2f6676a1162a.png">

**Comment by Omicsense** [comment] 2021-04-07 22:22
any recommendations

**Comment by gokalpcelik** [comment] 2021-04-13 14:34
Same issue here too. Please help. 

Thanks.

**Comment by MagdaKadlubowska** [comment] 2021-05-14 16:54
Same.

**Comment by katerinakazantseva** [comment] 2021-06-23 17:12
I have same issue

**Comment by ice-8** [comment] 2021-06-25 07:35
Hi

You need to add port mapping for incnv-frontend and incnv-backend for correct working. I don't have permissions to create a pull request, so try this changes:
```
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -6,6 +6,8 @@ services:
     restart: always
     networks:
       - incnv-network
+    ports:
+      - 80:80
   incnv-backend:
     image: saowwapark/incnv-backend:latest
     container_name: incnv-backend
@@ -27,6 +29,8 @@ services:
     depends_on:
       incnv-databases:
         condition: service_healthy
+    ports:
+      - 3000:3000
   incnv-databases:
     image: sakkayaphab/incnv-databases:latest
     container_name: incnv-databases
@@ -63,4 +67,4 @@ volumes:

```

**Comment by AmyOlex** [comment] 2021-07-26 18:00
The solution from @ice-8 worked for me.  Thanks!

**Comment by thaiszielke** [comment] 2021-10-19 01:16
Hi @AmyOlex and @ice-8 

How did you run it? I'm having the same issue. 
Did you run it through Ubuntu? I can't get it working :(

**Comment by dhwani2410** [comment] 2021-11-17 07:31
I am not able to sign up. I have a login error. PLease help me resolve the issue

**Comment by saowwapark** [comment] 2024-07-09 05:27
I apologize for replying late.

The root cause is the installation isn't finished. To install inCNV, the backend needs to download the datasources and add data into database. To complete the process, it takes big time but I didn't create the installation page to show the download status.

Right now I create the installation page. But it still has a limitation. "When downloading a datasource, users need to open only a single inCNV page in the browser and wait until it finishes. Users cannot refresh or open another inCNV page; otherwise, the installation will fail and require reinstallation (don't forget to remove associated Docker volumes). We apologize for this mistake. This will be fixed in the next release.", explained in https://github.com/saowwapark/inCNV/releases/tag/v2.2.0.

<img width="1061" alt="install-datasource" src="https://github.com/saowwapark/inCNV/assets/32361989/93da9c48-b0a6-4e94-bd18-2e685e114a58">

**Closed as completed by saowwapark** 2024-07-09 05:27 UTC
